#server
server:
  port: 80
  tomcat:
    max-threads: 1000
    min-spare-threads: 100
  servlet:
    context-path: /
#spring
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cwfkm?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
  servlet:
    multipart:
      max-request-size: 10MB
      file-size-threshold: 10MB
      max-file-size: 10MB  
#mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
  mapper-locations:
  - classpath:/mapper/*/*.xml
#log
logging:
  level:
    com: debug
db:
  page:
    page-size: 8

