spring:
  application:
    name: posty-service
  rabbitmq:
    host: 192.168.64.140
    port: 5672
    username: admin
    password: admin
  datasource:
    url: jdbc:mysql://localhost:3306/cwfkm?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
    
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
  mapper-locations:
  - classpath:/mapper/*/*.xml

server:
  port: 8201
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka  

management:
  endpoints:
    web:
      exposure:
        include: 
        - refresh
        - hystrix.stream